1725030309805	Sync.LogManager	DEBUG	Flushing file log
1725030309806	Sync.LogManager	DEBUG	Log cleanup threshold time: 1724166309806
1725030309806	Sync.LogManager	DEBUG	Done deleting files.
1725030323605	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change: scheduling a quick-write in 5000ms
1725030323693	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but a quick-write is already scheduled
1725030323745	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but a quick-write is already scheduled
1725030328657	Sync.Engine.Tabs	INFO	Can't do a quick-sync due to the service status: <Status: login: success.login, service: error.sync.failed, sync: error.login.reason.network>
1725030359702	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1725030359702	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1725030359706	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725030359707	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240819150008.desktop
1725030359707	Sync.Service	INFO	Starting sync at 2024-08-30 17:05:59 in browser session wdOBvE_6r0ah
1725030359707	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725030359711	Sync.Status	INFO	Resetting Status.
1725030359711	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1725030359711	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1725030360901	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1725030360901	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725030360902	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725030360905	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725030364721	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/260716208/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725030364721	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1725030364721	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1725030364721	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725030364722	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1725030364724	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
