1725029704157	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725030304789	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240819150008.desktop
1725030304789	Sync.Service	INFO	Starting sync at 2024-08-30 17:05:04 in browser session wdOBvE_6r0ah
1725030304789	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725030304792	Sync.Status	INFO	Resetting Status.
1725030304792	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1725030304793	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1725030304793	FirefoxAccounts	DEBUG	getOAuthToken enter
1725030304794	FirefoxAccounts	TRACE	getCachedToken returning cached token
1725030304794	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1725030304794	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1725030308004	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1725030308004	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725030308005	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725030308007	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725030309798	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1725030309798	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1725030309801	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/260716208/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725030309801	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1725030309801	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1725030309801	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725030309802	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1725030309804	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
